kind: HorizontalPodAutoscaler #Para este funcionar, a coleta de metricas, metrics-server, tem que estar rodando..
apiVersion: autoscaling/v1
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment #informe o name do deployment alvo
  minReplicas: 1
  maxReplicas: 3 #nunca cria mais replicas que isso
  targetCPUUtilizationPercentage: 30 #Quando chegar em 30% do consumo de CPU, ele scale up, mesmo de 30% scale down.

# kubectl apply -f 05-hpa.yaml
# kubectl get hpa
# Para realizar o teste de performance usei o fortio, conforme abaixo.:
# kubectl run -it fortio --rm --image=fortio/fortio -- load -qps 1800 -t 120s -c 70 "http://my-service/actuator/health"
# watch -n1 kubectl get hpa

# Obs.: Observei que os pods subiram, e quando o consumo zerou, eles desceram, mas demora, não desce de imadiato !