name: my-ci
on: [push]
jobs:
  my-publish-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: java install
        run: mvn clean install
      - name: List files
        run: ls -R
      - name: java execution
        run: java -jar target/purchase-order-0.0.1.jar