name: my-ci
on: [push]
jobs:
  my-publish-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: java -jar purchase-order-0.0.1.jar